spring.application.name=deploy


# 서버 설정
server.port=5000
server.servlet.context-path=/
server.servlet.encoding.charset=UTF-8

# 뷰리졸버 설정
spring.mvc.view.prefix=/WEB-INF/deploy/
spring.mvc.view.suffix=.jsp
